name: hasura_cache_interceptor
description: Package to implements cache in Hasura package
version: 1.0.0-dev.4
author: F-Team <david@flutterando.com.br>
homepage: https://flutterando.com.br
repository: https://github.com/Flutterando/hasura_cache_interceptor

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  uuid: ^2.2.0
  hasura_connect: ">=2.0.0-dev.17.6 <3.0.0"

dev_dependencies:
  http: ^0.12.2
  mockito: ^4.1.1
  test: ^1.15.3
